### ISSUE TITLE
"Deploy to Azure" button in readme has wrong link

### ISSUE THREAD

**Issue by mikeyk730** [Azure-Samples/service-fabric-cluster-templates#16]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
> 
"Deploy to Azure" button has wrong link on https://github.com/Azure-Samples/service-fabric-cluster-templates/blob/master/15-VM-Windows-Cross-AZ-Secure/README.md

Current link:
https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure-Samples%2Fservice-fabric-cluster-templates%2Fmaster%2F9-VM-Windows-Cross-AZ-UnSecure%2Fazuredeploy.json

Should be:
https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure-Samples%2Fservice-fabric-cluster-templates%2Fmaster%2F15-VM-Windows-Cross-AZ-Secure%2FAzureDeploy.json

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by mikeyk730** [comment]
"Visualize" button has the same issue

**Comment by craftyhouse** [comment]
Thanks, fixing

**Comment by craftyhouse** [comment]
https://github.com/Azure-Samples/service-fabric-cluster-templates/pull/68
