### ISSUE TITLE
what template to use to create cluster across regions

### ISSUE THREAD

**Issue by imhdev** [Azure-Samples/service-fabric-cluster-templates#63]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> I'm trying to span cluster across regions say east us, west us, east canada and what template to use to achieve this functionality?

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 10

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by craftyhouse** [comment]
Across regions is not supported, just across zones. https://github.com/Azure-Samples/service-fabric-cluster-templates/tree/master/15-VM-Windows-Cross-AZ-Secure
